# Generated by Django 5.2.6 on 2025-09-14 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liftosaur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('cloned_at', models.DateTimeField()),
                ('url', models.URLField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('vtype', models.CharField(max_length=50)),
                ('is_multiweek', models.BooleanField(default=False)),
                ('next_day', models.IntegerField(default=1)),
                ('planner_data', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('exercise_type_id', models.CharField(max_length=255)),
                ('equipment', models.CharField(max_length=100)),
                ('state', models.JSONField(blank=True, null=True)),
                ('variations', models.JSONField(default=list)),
                ('warmup_sets', models.JSONField(default=list)),
                ('finish_day_expr', models.TextField(blank=True, null=True)),
                ('timer_expr', models.CharField(blank=True, max_length=255, null=True)),
                ('enable_rpe', models.BooleanField(default=False)),
                ('enable_rep_ranges', models.BooleanField(default=False)),
                ('descriptions', models.JSONField(default=list)),
                ('diff_paths', models.JSONField(default=list)),
                ('deleted', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='liftosaur.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_num', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('days_data', models.JSONField(default=list)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='liftosaur.program')),
            ],
            options={
                'ordering': ['week_num'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_num', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('exercises_data', models.JSONField(default=list)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='liftosaur.program')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='liftosaur.programweek')),
            ],
            options={
                'ordering': ['day_num'],
            },
        ),
    ]
