# Generated by Django 5.2.6 on 2025-09-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liftosaur', '0002_program_programexercise_programweek_programday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programday',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programweek',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
