# Generated by Django 5.2.6 on 2025-09-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liftosaur', '0003_alter_programday_id_alter_programweek_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='program',
            name='user',
        ),
        migrations.RemoveField(
            model_name='programday',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programexercise',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programweek',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programday',
            name='week',
        ),
        migrations.RemoveField(
            model_name='set',
            name='workout_exercise',
        ),
        migrations.DeleteModel(
            name='BodyMeasurement',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProgramExercise',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='ProgramDay',
        ),
        migrations.DeleteModel(
            name='ProgramWeek',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
