# Generated by Django 5.2.6 on 2025-09-14 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liftosaur', '0006_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liftosaur.exercise'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='successes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_order', models.IntegerField()),
                ('reps', models.FloatField(blank=True, null=True)),
                ('weight_value', models.FloatField(blank=True, null=True)),
                ('weight_unit', models.CharField(blank=True, default='lb', max_length=10)),
                ('completed_reps', models.IntegerField(default=0)),
                ('completed_weight_value', models.FloatField(blank=True, null=True)),
                ('completed_weight_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('rpe', models.IntegerField(blank=True, null=True)),
                ('completed_rpe', models.IntegerField(blank=True, null=True)),
                ('is_amrap', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_warmup', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='liftosaur.workoutexercise')),
            ],
            options={
                'ordering': ['set_order'],
            },
        ),
    ]
