# Generated by Django 5.2.6 on 2025-09-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liftosaur', '0007_workoutexercise_exercise_workoutexercise_failures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
