services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - stack.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    working_dir: /app
    command: >
      sh -c "cd /app/Flexingg &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --reload Flexingg.wsgi:application"
    volumes:
      - .:/app
      - ./media:/app/Flexingg/media
    ports:
      - "1234:8000"
    env_file:
      - stack.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build: .
    working_dir: /app
    command: >
      sh -c "cd /app/Flexingg &&
             celery -A Flexingg.celery_app worker -l info"
    volumes:
      - .:/app
    env_file:
      - stack.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    build: .
    working_dir: /app
    command: >
      sh -c "cd /app/Flexingg &&
             celery -A Flexingg.celery_app beat -l info"
    volumes:
      - .:/app
    env_file:
      - stack.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
volumes:
  postgres_data: