services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flexingg_db
      - POSTGRES_USER=flexingg_user
      - POSTGRES_PASSWORD=flexingg_pass
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "cd Flexingg &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --reload Flexingg.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "1234:8000"
    environment:
      - DB_NAME=flexingg_db
      - DB_USER=flexingg_user
      - DB_PASSWORD=flexingg_pass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: >
      sh -c "cd Flexingg &&
             celery -A Flexingg worker -l info"
    volumes:
      - .:/app
    environment:
      - DB_NAME=flexingg_db
      - DB_USER=flexingg_user
      - DB_PASSWORD=flexingg_pass
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: >
      sh -c "cd Flexingg &&
             celery -A Flexingg beat -l info"
    volumes:
      - .:/app
    environment:
      - DB_NAME=flexingg_db
      - DB_USER=flexingg_user
      - DB_PASSWORD=flexingg_pass
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
volumes:
  postgres_data: