# Generated by Django 5.2.6 on 2025-09-17 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthConnectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('record_id', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField()),
                ('app_source', models.CharField(max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Connect Data',
                'verbose_name_plural': 'Health Connect Data',
                'ordering': ['-start_time'],
                'unique_together': {('profile', 'method', 'record_id')},
            },
        ),
    ]
