# Generated by Django 5.2.6 on 2025-10-03 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthconnect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='healthconnect', max_length=50)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('systolic', models.PositiveIntegerField()),
                ('diastolic', models.PositiveIntegerField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_pressure_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Pressure',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='BodyComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='healthconnect', max_length=50)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lean_mass_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('bone_mass_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('visceral_fat_index', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_composition', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Body Composition',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='BodyWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='healthconnect', max_length=50)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('weight_lbs', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_weights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Body Weight',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='healthconnect', max_length=50)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('activity_type', models.CharField(db_index=True, max_length=100)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('calories_burned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('total_power', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercise Session',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='HydrationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='healthconnect', max_length=50)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('volume_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_ounces', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydration_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hydration Entry',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='MenstruationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='healthconnect', max_length=50)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('average_flow', models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy'), ('spotting', 'Spotting')], max_length=16, null=True)),
                ('symptoms', models.JSONField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menstruation_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menstruation Period',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='healthconnect', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('metric', models.CharField(db_index=True, max_length=100)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metric Sample',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='NutritionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='healthconnect', max_length=50)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbs_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fat_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition Entry',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='SleepSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='healthconnect', max_length=50)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sleep Session',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='healthconnect', max_length=50)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('cadence', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('distance_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Step Record',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyHealthSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('steps_total', models.PositiveIntegerField(default=0)),
                ('calories_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('protein_grams_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('carbs_grams_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('fat_grams_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('water_ounces_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_health_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Health Summary',
                'ordering': ['-date'],
                'unique_together': {('profile', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HealthConnectRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(db_index=True, max_length=50)),
                ('record_id', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField()),
                ('app_source', models.CharField(blank=True, max_length=255)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_health_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raw Health Connect Data',
                'ordering': ['-start_time'],
                'unique_together': {('profile', 'method', 'record_id')},
            },
        ),
    ]
