# Generated by Django 5.2.6 on 2025-10-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthconnect', '0002_bloodpressure_bodycomposition_bodyweight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='sleep_minutes_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
