# Generated by Django 5.2.6 on 2025-10-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthconnect', '0003_dailyhealthsummary_sleep_minutes_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='active_calories_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
