# Generated by Django 5.1.1 on 2025-09-12 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garmin_Auth',
            fields=[
                ('oauth_token', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('oauth_token_secret', models.CharField(max_length=10000)),
                ('mfa_token', models.CharField(blank=True, max_length=10000, null=True)),
                ('mfa_expiration_timestamp', models.DateTimeField(blank=True, null=True)),
                ('domain', models.CharField(max_length=10000)),
                ('scope', models.CharField(max_length=10000)),
                ('jti', models.CharField(max_length=10000)),
                ('token_type', models.CharField(max_length=10000)),
                ('access_token', models.CharField(max_length=10000)),
                ('refresh_token', models.CharField(max_length=10000)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('expires_at', models.IntegerField(blank=True, null=True)),
                ('refresh_token_expires_in', models.IntegerField(blank=True, default=10000, null=True)),
                ('refresh_token_expires_at', models.IntegerField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Timestamp of the last successful data sync.', null=True)),
                ('last_sync_attempt', models.DateTimeField(blank=True, help_text='Timestamp of the last sync attempt (successful or failed).', null=True)),
                ('garmin_email', models.EmailField(blank=True, help_text='Garmin Connect email address used for linking.', max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GarminActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_id', models.BigIntegerField(help_text='Unique Garmin activity ID.', unique=True)),
                ('name', models.CharField(help_text='Name of the activity.', max_length=255)),
                ('activity_type', models.CharField(help_text='Type of activity (e.g., running, cycling).', max_length=100)),
                ('start_time_utc', models.DateTimeField(help_text='Start time of the activity in UTC.')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duration in seconds.', null=True)),
                ('distance_meters', models.FloatField(blank=True, help_text='Distance in meters.', null=True)),
                ('calories', models.FloatField(blank=True, help_text='Calories burned.', null=True)),
                ('average_hr', models.FloatField(blank=True, help_text='Average heart rate.', null=True)),
                ('max_hr', models.FloatField(blank=True, help_text='Maximum heart rate.', null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw JSON data from Garmin API.', null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garmin_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GarminCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('garmin_email', models.EmailField(help_text="User's Garmin Connect email address.", max_length=254, unique=True)),
                ('session_data', models.JSONField(blank=True, help_text='Garmin Connect session/token data.', null=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Timestamp of the last successful data sync.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garmin_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Garmin Credentials',
            },
        ),
        migrations.CreateModel(
            name='GarminDailySteps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='The date for which the steps were recorded.')),
                ('steps', models.PositiveIntegerField(help_text='Total steps recorded for the day.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garmin_daily_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Garmin Daily Steps',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
