# Generated by Django 5.2.6 on 2025-09-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garminconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmin_auth',
            name='liftosaur_user_id',
            field=models.CharField(blank=True, help_text='Liftosaur user ID for syncing workout data.', max_length=255, null=True),
        ),
    ]
