# Generated by Django 5.2.6 on 2025-09-20 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garminconnect', '0002_garmin_auth_liftosaur_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarminBodyWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_kg', models.FloatField(help_text='Weight in kilograms.')),
                ('datetime', models.DateTimeField(help_text='When the weight was recorded.')),
                ('source_type', models.CharField(default='garmin_scale', help_text="Source of the weight data (e.g., 'garmin_scale', 'manual_entry').", max_length=50)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw JSON data from Garmin API.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garmin_body_weights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garmin Body Weight',
                'verbose_name_plural': 'Garmin Body Weights',
                'ordering': ['-datetime'],
                'unique_together': {('user', 'datetime')},
            },
        ),
    ]
