# Generated by Django 5.2.6 on 2025-09-07 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sweatscoreweights_alter_dailystep_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garminactivity',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dailysteps',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='garmindailysteps',
            name='synced_at',
        ),
        migrations.CreateModel(
            name='ColorPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(default='#121212', help_text='Surface color', max_length=7)),
                ('on_surface', models.CharField(default='#FFFFFF', help_text='On surface color', max_length=7)),
                ('primary', models.CharField(default='#00f5d4', help_text='Primary color', max_length=7)),
                ('on_primary', models.CharField(default='#000000', help_text='On primary color', max_length=7)),
                ('secondary', models.CharField(default='#2a2a2a', help_text='Secondary color', max_length=7)),
                ('on_secondary', models.CharField(default='#FFFFFF', help_text='On secondary color', max_length=7)),
                ('tertiary', models.CharField(default='#333333', help_text='Tertiary color', max_length=7)),
                ('on_tertiary', models.CharField(default='#FFFFFF', help_text='On tertiary color', max_length=7)),
                ('surface_variant', models.CharField(default='#1f1f1f', help_text='Surface variant color', max_length=7)),
                ('on_surface_variant', models.CharField(default='#BDBDBD', help_text='On surface variant color', max_length=7)),
                ('outline', models.CharField(default='#424242', help_text='Outline color', max_length=7)),
                ('error', models.CharField(default='#F44336', help_text='Error color', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_colors', to='core.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
