# Generated by Django 5.1.1 on 2025-09-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_garminactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height_ft',
            field=models.IntegerField(blank=True, help_text='Height in feet', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_in',
            field=models.IntegerField(blank=True, help_text='Height in inches', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Gender', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in lbs.', max_digits=5, null=True),
        ),
    ]
