# Generated by Django 5.1.1 on 2025-09-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userprofile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sync_debounce_minutes',
            field=models.IntegerField(blank=True, default=60, help_text='Minutes between automatic Garmin syncs (default: 60)', null=True),
        ),
    ]
