# Generated by Django 5.2.6 on 2025-09-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_sync_debounce_minutes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailysteps',
            unique_together={('user', 'calendar_date')},
        ),
    ]
