# Generated by Django 5.2.6 on 2025-09-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liftosaur_user_id',
            field=models.CharField(blank=True, help_text='Liftosaur user ID for integration', max_length=255, null=True),
        ),
    ]
