# Generated by Django 5.2.6 on 2025-09-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_liftosaur_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liftosaur_session_token',
            field=models.CharField(blank=True, help_text='Liftosaur session token for API access', max_length=255, null=True),
        ),
    ]
