# Generated by Django 5.2.6 on 2025-09-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_liftosaur_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hc_password',
            field=models.CharField(blank=True, help_text='HCGateway password (hashed)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hc_refresh_token',
            field=models.TextField(blank=True, help_text='HCGateway refresh token', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hc_token',
            field=models.TextField(blank=True, help_text='HCGateway access token', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hc_token_expiry',
            field=models.DateTimeField(blank=True, help_text='Token expiry time', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hc_username',
            field=models.CharField(blank=True, help_text='HCGateway username', max_length=255, null=True),
        ),
    ]
