# Generated by Django 5.2.6 on 2025-09-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile_hc_password_userprofile_hc_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hc_last_sync',
            field=models.DateTimeField(blank=True, help_text='Last Health Connect sync time', null=True),
        ),
    ]
