# Generated by Django 5.2.6 on 2025-09-19 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_userprofile_hc_last_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        choices=[
                            ("garmin", "Garmin"),
                            ("healthconnect", "Health Connect"),
                            ("liftosaur", "Liftosaur"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "auth_data",
                    models.JSONField(
                        help_text="Stores authentication tokens and other service-specific data."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connected_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Connected Service",
                "verbose_name_plural": "Connected Services",
                "unique_together": {("user", "service_name")},
            },
        ),
        migrations.CreateModel(
            name="DailySteps",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField()),
                ("steps", models.PositiveIntegerField()),
                (
                    "data",
                    models.JSONField(
                        blank=True, help_text="Normalized steps data", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unified_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Steps",
                "verbose_name_plural": "Daily Steps",
                "ordering": ["-date"],
                "unique_together": {("user", "source", "date")},
            },
        ),
        migrations.CreateModel(
            name="DataPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("workout", "Workout"),
                            ("sleep", "Sleep"),
                            ("steps", "Steps"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("garmin", "Garmin"),
                            ("healthconnect", "Health Connect"),
                            ("liftosaur", "Liftosaur"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rank", models.IntegerField(help_text="Priority rank (1 is highest)")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_priorities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Priority",
                "verbose_name_plural": "Data Priorities",
                "ordering": ["user", "data_type", "rank"],
                "unique_together": {("user", "data_type", "rank")},
            },
        ),
        migrations.CreateModel(
            name="Sleep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("source_id", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("data", models.JSONField(help_text="Normalized sleep data")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unified_sleep",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sleep",
                "verbose_name_plural": "Sleep Data",
                "ordering": ["-start_time"],
                "unique_together": {("user", "source", "source_id")},
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("source_id", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("data", models.JSONField(help_text="Normalized workout data")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unified_workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout",
                "verbose_name_plural": "Workouts",
                "ordering": ["-start_time"],
                "unique_together": {("user", "source", "source_id")},
            },
        ),
    ]
