# Generated by Django 5.2.6 on 2025-09-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_create_unified_workout_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedworkoutset',
            name='set_order',
            field=models.IntegerField(),
        ),
    ]
