# Generated by Django 5.2.6 on 2025-09-20 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_unifiedworkoutset_set_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField()),
                ('weight_lbs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data', models.JSONField(blank=True, help_text='Normalized weight data', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_weights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Body Weight',
                'verbose_name_plural': 'Body Weight Entries',
                'ordering': ['-datetime'],
                'unique_together': {('user', 'source', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='DailyWater',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('amount_ounces', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data', models.JSONField(blank=True, help_text='Normalized water data', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_water', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Water',
                'verbose_name_plural': 'Daily Water Intake',
                'ordering': ['-date'],
                'unique_together': {('user', 'source', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NutritionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('food_name', models.CharField(max_length=255)),
                ('quantity_description', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('protein_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fat_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbs_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('data', models.JSONField(blank=True, help_text='Normalized nutrition data', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_nutrition', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition Entry',
                'verbose_name_plural': 'Nutrition Entries',
                'ordering': ['-datetime'],
                'unique_together': {('user', 'source', 'source_id')},
            },
        ),
    ]
