# Generated by Django 4.2 on 2025-01-20 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_bodyweight_dailywater_nutritionentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedWorkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('data', models.JSONField(help_text='Original workout data before archiving')),
                ('archived_reason', models.CharField(choices=[('lower_priority', 'Lower Priority Source'), ('time_conflict', 'Time Conflict'), ('data_conflict', 'Data Conflict')], max_length=100)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('linked_primary_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_archived_workouts', to='core.workout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_workouts', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Archived Workout',
                'verbose_name_plural': 'Archived Workouts',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('time_overlap', 'Time Overlap'), ('data_mismatch', 'Data Mismatch'), ('duplicate_activity', 'Duplicate Activity')], max_length=50)),
                ('conflict_score', models.FloatField(help_text='Confidence score of the conflict (0-1)')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_method', models.CharField(blank=True, choices=[('auto_priority', 'Automatic Priority'), ('manual_review', 'Manual Review'), ('data_merge', 'Data Merge')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_conflicts', to='core.archivedworkout')),
                ('primary_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_conflicts', to='core.workout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_conflicts', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Workout Conflict',
                'verbose_name_plural': 'Workout Conflicts',
                'ordering': ['-created_at'],
            },
        ),
    ]