# Generated by Django 5.2.6 on 2025-09-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_archivedworkout_workoutconflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapriority',
            name='data_type',
            field=models.CharField(choices=[('workout', 'Workout'), ('sleep', 'Sleep'), ('steps', 'Steps'), ('water', 'Water')], max_length=50),
        ),
    ]
