# Generated by Django 5.2.6 on 2025-09-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_datapriority_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('xp_required', models.BigIntegerField(help_text='Cumulative XP required to reach this level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'ordering': ['level_number'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='xp_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bodyweight_lbs',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text='Fallback bodyweight in lbs when synced weight is unavailable', max_digits=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cardio_coins_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Personal multiplier for CardioCoins earnings', max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gym_gems_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Personal multiplier for GymGems earnings', max_digits=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency_type',
            field=models.CharField(choices=[('cardio_coins', 'Cardio Coins'), ('gym_gems', 'Gym Gems'), ('xp', 'Experience Points')], max_length=20),
        ),
    ]
