# Generated by Django 5.2.6 on 2025-09-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_populate_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last general sync', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stat_card_config',
            field=models.JSONField(blank=True, default=list, help_text='Configuration for stat card order and visibility.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sync_debounce_minutes',
            field=models.IntegerField(blank=True, default=60, help_text='Minutes between automatic general syncs (default: 60)', null=True),
        ),
    ]
