# Generated by Django 5.2.6 on 2025-09-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userprofile_last_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_sync',
        ),
    ]
