# Generated by Django 5.2.6 on 2025-09-27 00:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userprofile_last_sync_userprofile_stat_card_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idea_text', models.CharField(help_text='Short description of the integration idea', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional metadata (e.g., user agent, source)', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted the idea (nullable for anonymous suggestions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration Idea',
                'verbose_name_plural': 'Integration Ideas',
                'ordering': ['-created_at'],
            },
        ),
    ]
