# Generated by Django 5.2.6 on 2025-09-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_userprofile_last_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last general sync', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sync_debounce_minutes',
            field=models.IntegerField(blank=True, default=60, help_text='Minutes between automatic general syncs (default: 60)', null=True),
        ),
    ]
