# Generated by Django 5.2.6 on 2025-09-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_integrationidea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapriority',
            name='data_type',
            field=models.CharField(choices=[('workout', 'Workout'), ('sleep', 'Sleep'), ('steps', 'Steps'), ('water', 'Water'), ('bodyweight', 'Bodyweight')], max_length=50),
        ),
    ]
