# Generated by Django 5.2.6 on 2025-10-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_datapriority_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bodyweight_lbs',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Fallback bodyweight in lbs when synced weight is unavailable', max_digits=6),
        ),
    ]
