# Generated by Django 5.2.6 on 2025-09-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_userprofile_last_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stat_card_config',
            field=models.JSONField(blank=True, default=list, help_text='Configuration for stat card order and visibility.'),
        ),
    ]
